name = "CorticalSpectralTemporalResponses"
uuid = "82ec0db2-aa68-11e9-08e4-e3d69fc08b96"
authors = ["David Little <david.frank.little@gmail.com>"]
version = "0.4.1"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MetaArrays = "36b8f3f0-b776-11e8-061f-1f20094e1fc8"
PlotAxes = "8b6f5f00-d239-11e8-3a24-33314b00f6b0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"
AxisArrays = "0.3"
Colors = "0.9"
Compat = "2"
DSP = "0.5.1, 0.6"
FFTW = "0.2.4, 0.3, 1"
FileIO = "1"
ImageInTerminal = "0.4"
JLD2 = "0.1"
MetaArrays = "0.2, 0.3"
PlotAxes = "0.2.4"
ProgressMeter = "0.6,0.7,0.8,0.9,1"
Requires = "0.5.2"
SampledSignals = "2"
Unitful = "0.11,0.12,0.13,0.14,0.15,0.16,0.17"
